// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAT-1RjqUYRj16JQ9fmwZ_ODi9LGCVpo8g',
    appId: '1:709410727200:web:d7723ec802c27b3590a345',
    messagingSenderId: '709410727200',
    projectId: 'chattrix-b2bd9',
    authDomain: 'chattrix-b2bd9.firebaseapp.com',
    storageBucket: 'chattrix-b2bd9.firebasestorage.app',
    measurementId: 'G-S0Z7NE21DM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuasoU0Iw-AFaskNFs2S_btCd7BLp7WNU',
    appId: '1:709410727200:android:7d0a83b722aad51d90a345',
    messagingSenderId: '709410727200',
    projectId: 'chattrix-b2bd9',
    storageBucket: 'chattrix-b2bd9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALLPXb6EnYzAufK558wpzhJbHom8FBehg',
    appId: '1:709410727200:ios:00815062a093713a90a345',
    messagingSenderId: '709410727200',
    projectId: 'chattrix-b2bd9',
    storageBucket: 'chattrix-b2bd9.firebasestorage.app',
    iosBundleId: 'com.example.chattrix',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALLPXb6EnYzAufK558wpzhJbHom8FBehg',
    appId: '1:709410727200:ios:00815062a093713a90a345',
    messagingSenderId: '709410727200',
    projectId: 'chattrix-b2bd9',
    storageBucket: 'chattrix-b2bd9.firebasestorage.app',
    iosBundleId: 'com.example.chattrix',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAT-1RjqUYRj16JQ9fmwZ_ODi9LGCVpo8g',
    appId: '1:709410727200:web:c1dafe8a1bfe647490a345',
    messagingSenderId: '709410727200',
    projectId: 'chattrix-b2bd9',
    authDomain: 'chattrix-b2bd9.firebaseapp.com',
    storageBucket: 'chattrix-b2bd9.firebasestorage.app',
    measurementId: 'G-YC7XY94GJ3',
  );
}
